# Generated by Django 3.2.4 on 2021-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('aliases', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('casting', models.ManyToManyField(related_name='movies_as_char', to='cine.Person')),
                ('directors', models.ManyToManyField(related_name='movies_as_dir', to='cine.Person')),
                ('producers', models.ManyToManyField(related_name='movies_as_prod', to='cine.Person')),
            ],
        ),
    ]
