# Generated by Django 3.2.4 on 2021-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveSmallIntegerField(default=1800),
            preserve_default=False,
        ),
    ]
